[package]
name = "site-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
markdown = "1.0.0-alpha.14"
notify = "6.1.1"
notify-debouncer-mini = "0.4.1"
rayon = "1.8.0"
